# Generated by Django 5.0.4 on 2024-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=79)),
                ('category_id', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('fling_power', models.IntegerField(blank=True, null=True)),
                ('fling_effect_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
