# Generated by Django 5.0.4 on 2024-04-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EggGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=79)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_id', models.IntegerField(default=None, null=True)),
                ('identifier', models.CharField(max_length=79)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=79)),
                ('generation_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('power', models.SmallIntegerField(default=None, null=True)),
                ('pp', models.SmallIntegerField(default=None, null=True)),
                ('accuracy', models.SmallIntegerField(default=None, null=True)),
                ('priority', models.SmallIntegerField()),
                ('target_id', models.IntegerField()),
                ('damage_class_id', models.IntegerField()),
                ('effect_id', models.IntegerField()),
                ('effect_chance', models.IntegerField(default=None, null=True)),
                ('contest_type_id', models.IntegerField(default=None, null=True)),
                ('contest_effect_id', models.IntegerField(default=None, null=True)),
                ('super_contest_effect_id', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=79)),
                ('species_id', models.IntegerField(default=None, null=True)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('base_experience', models.IntegerField()),
                ('order', models.IntegerField()),
                ('is_default', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEggGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.IntegerField()),
                ('egg_group_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonFormGenerations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_form_id', models.IntegerField()),
                ('generation_id', models.IntegerField()),
                ('game_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonMoves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('version_group_id', models.IntegerField()),
                ('move_id', models.IntegerField()),
                ('pokemon_move_method_id', models.IntegerField()),
                ('level', models.IntegerField()),
                ('order', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('stat_id', models.IntegerField()),
                ('base_stat', models.IntegerField()),
                ('effort', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('slot', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('damage_class_id', models.IntegerField(default=None, null=True)),
                ('identifier', models.CharField(max_length=79)),
                ('is_battle_only', models.BooleanField()),
                ('game_index', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=79)),
                ('generation_id', models.IntegerField()),
                ('damage_class_id', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
