# Generated by Django 5.0.4 on 2024-04-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_egggroup_location_move_pokemon_pokemonegggroups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('pokemon_id', models.IntegerField()),
            ],
        ),
    ]
